# Auto-generated by matugen — Material You
#
# ── Why fish gets its own colour file (quick task 260818-nwo) ────────────
# kitty runs fish (`kitty.conf`: `shell fish`), so fish's syntax highlighting
# is the terminal's most-read colour surface. Left to its own defaults fish
# resolves everything through the 16 ANSI slots, which forces two unrelated
# jobs onto one mapping: "be a faithful ANSI palette" and "make a command
# line readable". Material You supplies four chromatic roles (primary,
# secondary, tertiary, error); ANSI wants six distinct hues. Something has to
# give, and with only the ANSI mapping to work with it was always the command
# line that lost.
#
# The two-step history this file closes:
#   1. `fish_color_param` defaults to `cyan` -> ANSI slot 6, which the kitty
#      template mapped to `secondary_container` — a Material You BACKGROUND
#      role. Measured 1.98:1 live and 1.10-1.56:1 across all 20 static
#      palettes, i.e. every command argument was effectively invisible.
#   2. Remapping slot 6 to `on_secondary_container` fixed the contrast
#      (14.42:1) but landed on a near-white that is ~indistinguishable from
#      the default foreground — so arguments became legible and lost their
#      distinction from the command instead. Reported back as exactly that.
#
# Assigning fish's classes directly, from named roles, decouples the two
# problems: the ANSI palette can stay a readable ANSI palette, and the
# command line can be composed deliberately.
#
# ── The assignment, and the measurement behind it ───────────────────────
# `fish_color_command` defaults to `normal` — plain foreground — so a command
# was never accented in the first place. It gets `primary`, the theme's
# signature colour. Arguments are the highest-volume text on the line and the
# thing originally reported as unreadable, so they get `on_surface`: measured
# >= 4.5:1 against `background` in ALL 20 static palettes (worst 4.5,
# tokyonight-day), the only class of role that clears AA everywhere.
#
# Command-vs-argument separation, measured as CIE76 dE across all 20 static
# palettes: worst 13.2 (tokyonight-day), typical 25-88. Clearly two colours
# in every theme, not a shade apart.
#
# Comments and autosuggestions deliberately use `outline`, a LOW-contrast
# role: both are meant to recede, so the usual contrast floor does not apply
# to them and applying it would make them shout.
#
# KNOWN RESIDUAL: in four light palettes (gruvbox-light 2.2:1, rosepine-dawn
# 2.6:1, tokyonight-day 3.1:1, miasma 3.9:1) `primary` itself is under AA, so
# the COMMAND token is weak there. That is the same pre-existing light-palette
# accent weakness that also affects the shipped `error`/`tertiary`/`secondary`
# slots, not something introduced here — and it is confined to the short
# command token while the bulk of the line stays legible. Fixing it means
# editing those palette files.

# ── Every value below is SINGLE-QUOTED, and must stay that way ──────────
# `#` opens a comment in fish. Unquoted, `set -g fish_color_command #b3c5ff`
# parses as `set -g fish_color_command` followed by a comment — fish sets the
# variable to EMPTY and exits 0, so the file sources cleanly, reports no
# error, and silently themes nothing. Caught here only by reading the
# variables back after sourcing rather than trusting the exit code.
# The same applies to the `--background=#...` forms, which are quoted whole.

# Command / keyword — the theme accent.
set -g fish_color_command '{{colors.primary.default.hex}}'
set -g fish_color_keyword '{{colors.primary.default.hex}}'

# Arguments — the highest-volume text; the only AA-safe-everywhere role.
set -g fish_color_param '{{colors.on_surface.default.hex}}'

# Flags/options — distinct from a bare argument without competing with it.
set -g fish_color_option '{{colors.secondary.default.hex}}'

# Quoted strings and operators.
set -g fish_color_quote '{{colors.tertiary.default.hex}}'
set -g fish_color_operator '{{colors.tertiary.default.hex}}'
set -g fish_color_redirection '{{colors.secondary.default.hex}}'
set -g fish_color_end '{{colors.on_surface_variant.default.hex}}'

# Errors — the palette's own error role, never a hardcoded red.
set -g fish_color_error '{{colors.error.default.hex}}'

# Deliberately receding (see note above).
set -g fish_color_comment '{{colors.outline.default.hex}}'
set -g fish_color_autosuggestion '{{colors.outline.default.hex}}'

# Selection/search surfaces.
set -g fish_color_search_match '--background={{colors.surface_variant.default.hex}}'
set -g fish_color_selection '--background={{colors.surface_variant.default.hex}}'

# Completion pager.
set -g fish_pager_color_prefix '{{colors.primary.default.hex}}'
set -g fish_pager_color_completion '{{colors.on_surface.default.hex}}'
set -g fish_pager_color_description '{{colors.outline.default.hex}}'
set -g fish_pager_color_selected_background '--background={{colors.surface_variant.default.hex}}'
