# Auto-generated by matugen — Material You
#
# ── Why fish gets its own colour file (quick task 260818-nwo) ────────────
# kitty runs fish (`kitty.conf`: `shell fish`), so fish's syntax highlighting
# is the terminal's most-read colour surface. Left to its own defaults fish
# resolves everything through the 16 ANSI slots, which forces two unrelated
# jobs onto one mapping: "be a faithful ANSI palette" and "make a command
# line readable". Material You supplies four chromatic roles (primary,
# secondary, tertiary, error); ANSI wants six distinct hues. Something has to
# give, and with only the ANSI mapping to work with it was always the command
# line that lost.
#
# The two-step history this file closes:
#   1. `fish_color_param` defaults to `cyan` -> ANSI slot 6, which the kitty
#      template mapped to `secondary_container` — a Material You BACKGROUND
#      role. Measured 1.98:1 live and 1.10-1.56:1 across all 20 static
#      palettes, i.e. every command argument was effectively invisible.
#   2. Remapping slot 6 to `on_secondary_container` fixed the contrast
#      (14.42:1) but landed on a near-white that is ~indistinguishable from
#      the default foreground — so arguments became legible and lost their
#      distinction from the command instead. Reported back as exactly that.
#
# Assigning fish's classes directly, from named roles, decouples the two
# problems: the ANSI palette can stay a readable ANSI palette, and the
# command line can be composed deliberately.
#
# ── The assignment, and the measurement behind it ───────────────────────
# `fish_color_command` defaults to `normal` — plain foreground — so a command
# was never accented in the first place. It gets `primary`, the theme's
# signature colour. Arguments get `tertiary` (see the note at that line for
# the three candidates measured and why this one was chosen over the
# AA-safe-everywhere alternative).
#
# Comments and autosuggestions deliberately use `outline`, a LOW-contrast
# role: both are meant to recede, so the usual contrast floor does not apply
# to them and applying it would make them shout.
#
# KNOWN RESIDUAL: in four light palettes (gruvbox-light 2.2:1, rosepine-dawn
# 2.6:1, tokyonight-day 3.1:1, miasma 3.9:1) `primary` itself is under AA, so
# the COMMAND token is weak there. That is the same pre-existing light-palette
# accent weakness that also affects the shipped `error`/`tertiary`/`secondary`
# slots, not something introduced here — and it is confined to the short
# command token while the bulk of the line stays legible. Fixing it means
# editing those palette files.

# ── Every value below is SINGLE-QUOTED, and must stay that way ──────────
# `#` opens a comment in fish. Unquoted, `set -g fish_color_command #b3c5ff`
# parses as `set -g fish_color_command` followed by a comment — fish sets the
# variable to EMPTY and exits 0, so the file sources cleanly, reports no
# error, and silently themes nothing. Caught here only by reading the
# variables back after sourcing rather than trusting the exit code.
# The same applies to the `--background=#...` forms, which are quoted whole.

# Command / keyword — the theme accent.
set -g fish_color_command '{{colors.primary.default.hex}}'
set -g fish_color_keyword '{{colors.primary.default.hex}}'

# Arguments — `tertiary`, operator-selected 2026-08-18 from three measured
# candidates. The first pass used `on_surface` (plain foreground): AA-safe in
# all 20 palettes, but that IS the default text colour, so arguments read as
# undifferentiated body text and the command/argument distinction was reported
# lost a second time. `tertiary` is the furthest of the available roles from
# both the blue command and plain white — live dE 22.8 from `primary` and 21.8
# from `on_surface`, at 10.9:1 against the background.
#
# Accepted trade-off, chosen with the numbers on the table: in the five light
# palettes `tertiary` drops to ~2.96:1, below AA. That is the same pre-existing
# light-palette accent weakness that already affects the shipped
# `error`/`secondary`/`primary` slots there — not a new failure mode — and the
# alternative that cleared AA everywhere (`on_primary_container`, worst 4.52:1)
# was too close to plain white to solve the reported problem.
set -g fish_color_param '{{colors.tertiary.default.hex}}'

# Flags/options — distinct from a bare argument without competing with it.
set -g fish_color_option '{{colors.secondary.default.hex}}'

# Quoted strings and operators — moved OFF `tertiary` when arguments took it,
# so a quoted argument stays distinguishable from a bare one rather than both
# collapsing to the same colour. `on_primary_container` is the soft tinted
# off-white that clears AA in all 20 palettes (worst 4.52:1).
set -g fish_color_quote '{{colors.on_primary_container.default.hex}}'
set -g fish_color_operator '{{colors.on_primary_container.default.hex}}'
set -g fish_color_redirection '{{colors.secondary.default.hex}}'
set -g fish_color_end '{{colors.on_surface_variant.default.hex}}'

# Errors — the palette's own error role, never a hardcoded red.
set -g fish_color_error '{{colors.error.default.hex}}'

# Deliberately receding (see note above).
set -g fish_color_comment '{{colors.outline.default.hex}}'
set -g fish_color_autosuggestion '{{colors.outline.default.hex}}'

# Selection/search surfaces.
set -g fish_color_search_match '--background={{colors.surface_variant.default.hex}}'
set -g fish_color_selection '--background={{colors.surface_variant.default.hex}}'

# Completion pager.
set -g fish_pager_color_prefix '{{colors.primary.default.hex}}'
set -g fish_pager_color_completion '{{colors.on_surface.default.hex}}'
set -g fish_pager_color_description '{{colors.outline.default.hex}}'
set -g fish_pager_color_selected_background '--background={{colors.surface_variant.default.hex}}'
