-- Auto-generated by matugen — Material You dynamic colors (Lua table fragment)
-- Do NOT edit manually — changes will be overwritten
--
-- Consumed ONCE by theme-engine/lib/motion.sh's theme_engine_render_hypr_tokens,
-- which merges this fragment into the single generated hyprland-tokens.lua
-- table and then deletes this file from the tmp render tree — this
-- fragment itself NEVER reaches ~/.local/state/theme/ and has no
-- contract.json entry of its own (D-02/D-05). Additive alongside
-- hyprland-colors.conf (unchanged) — the hyprlang output is still the
-- D-12 rollback target's input and must keep being produced.
--
-- Same 21 assignments (20 colour roles + the deliberately blank `image`
-- placeholder), same names, same matugen colour placeholder forms, same
-- rgba(...ff) wrapping, and the same literal rgba(00000055) for shadow as
-- hyprland-colors.conf — this is a syntax re-wrap (Lua table literal
-- instead of hyprlang `$name = value`), not a behaviour or value-set
-- change.
return {
    primary = "rgba({{colors.primary.default.hex_stripped}}ff)",
    on_primary = "rgba({{colors.on_primary.default.hex_stripped}}ff)",
    primary_container = "rgba({{colors.primary_container.default.hex_stripped}}ff)",
    on_primary_container = "rgba({{colors.on_primary_container.default.hex_stripped}}ff)",
    secondary = "rgba({{colors.secondary.default.hex_stripped}}ff)",
    on_secondary = "rgba({{colors.on_secondary.default.hex_stripped}}ff)",
    secondary_container = "rgba({{colors.secondary_container.default.hex_stripped}}ff)",
    on_secondary_container = "rgba({{colors.on_secondary_container.default.hex_stripped}}ff)",
    tertiary = "rgba({{colors.tertiary.default.hex_stripped}}ff)",
    on_tertiary = "rgba({{colors.on_tertiary.default.hex_stripped}}ff)",
    surface = "rgba({{colors.surface.default.hex_stripped}}ff)",
    on_surface = "rgba({{colors.on_surface.default.hex_stripped}}ff)",
    surface_variant = "rgba({{colors.surface_variant.default.hex_stripped}}ff)",
    on_surface_variant = "rgba({{colors.on_surface_variant.default.hex_stripped}}ff)",
    background = "rgba({{colors.background.default.hex_stripped}}ff)",
    on_background = "rgba({{colors.on_background.default.hex_stripped}}ff)",
    outline = "rgba({{colors.outline.default.hex_stripped}}ff)",
    shadow = "rgba(00000055)",
    error = "rgba({{colors.error.default.hex_stripped}}ff)",
    on_error = "rgba({{colors.on_error.default.hex_stripped}}ff)",

    -- $image intentionally blank: matugen 4.1.0 does not populate the image
    -- color context in either json or image render mode (empirically
    -- verified during Plan 01-02) - referencing it throws a hard
    -- ResolveError regardless of render mode. hyprlock theming is out of
    -- scope this milestone (PROJECT.md); an empty string here is
    -- sufficient and does not break template rendering.
    image = "",
}
