-- Auto-generated by matugen — Material You dynamic colors (Lua table)
-- Do NOT edit manually — changes will be overwritten
--
-- Consumed by nvim/.config/nvim/lua/theme/palette.lua, which `dofile`s this
-- exact path (~/.local/state/theme/nvim.lua) fresh on every colorscheme
-- load. ROLES ONLY — twelve Material You role colours, nothing more. This
-- file must NEVER learn what a syntax slot is: nvim/.config/nvim/lua/theme/
-- ramp.lua derives keyword/string/function/etc. from these roles in Lua at
-- load time, because a text template cannot do colour math. Widening this
-- file to carry syntax colours directly would duplicate that logic in a
-- place that cannot compute it.
--
-- Eight of the twelve feed the ramp (surface, on_surface, surface_variant,
-- on_surface_variant, outline, primary, secondary, tertiary, error); the
-- remaining four (on_primary, primary_container, on_primary_container) plus
-- surface_variant serve the editor's own UI chrome — cursorline, selection
-- and statusline backgrounds — that the ramp does not compute.
return {
    surface = "{{colors.surface.default.hex}}",
    on_surface = "{{colors.on_surface.default.hex}}",
    surface_variant = "{{colors.surface_variant.default.hex}}",
    on_surface_variant = "{{colors.on_surface_variant.default.hex}}",
    outline = "{{colors.outline.default.hex}}",
    primary = "{{colors.primary.default.hex}}",
    on_primary = "{{colors.on_primary.default.hex}}",
    primary_container = "{{colors.primary_container.default.hex}}",
    on_primary_container = "{{colors.on_primary_container.default.hex}}",
    secondary = "{{colors.secondary.default.hex}}",
    tertiary = "{{colors.tertiary.default.hex}}",
    error = "{{colors.error.default.hex}}",
}
