# ~/.dotfiles/kitty/.config/kitty/kitty.conf

# Import the color theme
include theme.conf

# Fonts
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13.0

# Window layout
window_padding_width 12
hide_window_decorations yes
confirm_os_window_close 0

# Transparency (Allows Hyprland blur to work)
background_opacity 0.85
dynamic_background_opacity yes

# Wayland native
linux_display_server wayland

# Performance
repaint_delay 10
input_delay 3
sync_to_monitor yes

# Allow live-reloading of colors
allow_remote_control yes
listen_on unix:/tmp/kitty