# ~/.dotfiles/matugen/.config/matugen/templates/kitty-colors.conf

foreground #e7e0e8
background #141218
selection_foreground #141218
selection_background #cdc2db
cursor #d2bcfd
cursor_text_color #141218

color0 #36343a
color8 #948f99

color1 #ffb4ab
color9 #ffb4ab

color2 #f0b8c6
color10 #f0b8c6

color3 #cdc2db
color11 #cdc2db

color4 #d2bcfd
color12 #d2bcfd

color5 #eaddff
color13 #eaddff

color6 #e9def8
color14 #e9def8

color7 #cbc4cf
color15 #e7e0e8