# Catppuccin Mocha
$primary = rgba(cba6f7ff)
$on_primary = rgba(1e1e2eff)
$primary_container = rgba(45475aff)
$on_primary_container = rgba(cdd6f4ff)
$secondary = rgba(f5c2e7ff)
$on_secondary = rgba(1e1e2eff)
$secondary_container = rgba(45475aff)
$on_secondary_container = rgba(f5c2e7ff)
$tertiary = rgba(94e2d5ff)
$on_tertiary = rgba(1e1e2eff)
$surface = rgba(1e1e2eff)
$on_surface = rgba(cdd6f4ff)
$surface_variant = rgba(313244ff)
$on_surface_variant = rgba(a6adc8ff)
$background = rgba(1e1e2eff)
$on_background = rgba(cdd6f4ff)
$outline = rgba(585b70ff)
$shadow = rgba(00000055)
$error = rgba(f38ba8ff)
$on_error = rgba(1e1e2eff)
