# Gruvbox Dark
$primary = rgba(d79921ff)
$on_primary = rgba(282828ff)
$primary_container = rgba(3c3836ff)
$on_primary_container = rgba(ebdbb2ff)
$secondary = rgba(b8bb26ff)
$on_secondary = rgba(282828ff)
$secondary_container = rgba(3c3836ff)
$on_secondary_container = rgba(b8bb26ff)
$tertiary = rgba(8ec07cff)
$on_tertiary = rgba(282828ff)
$surface = rgba(282828ff)
$on_surface = rgba(ebdbb2ff)
$surface_variant = rgba(3c3836ff)
$on_surface_variant = rgba(a89984ff)
$background = rgba(282828ff)
$on_background = rgba(ebdbb2ff)
$outline = rgba(504945ff)
$shadow = rgba(00000055)
$error = rgba(fb4934ff)
$on_error = rgba(282828ff)
