# Tokyo Night
$primary = rgba(7aa2f7ff)
$on_primary = rgba(1a1b26ff)
$primary_container = rgba(24283bff)
$on_primary_container = rgba(c0caf5ff)
$secondary = rgba(bb9af7ff)
$on_secondary = rgba(1a1b26ff)
$secondary_container = rgba(24283bff)
$on_secondary_container = rgba(bb9af7ff)
$tertiary = rgba(7dcfffff)
$on_tertiary = rgba(1a1b26ff)
$surface = rgba(1a1b26ff)
$on_surface = rgba(c0caf5ff)
$surface_variant = rgba(24283bff)
$on_surface_variant = rgba(a9b1d6ff)
$background = rgba(1a1b26ff)
$on_background = rgba(c0caf5ff)
$outline = rgba(414868ff)
$shadow = rgba(00000055)
$error = rgba(f7768eff)
$on_error = rgba(1a1b26ff)
