-- hypr/.config/hypr/config/permissions.lua — Lua port of
-- config/permissions.conf (Phase 13.1, plan 13.1-07, D-12, 11-05).
-- Hyprland's dynamic-client permission manager.
--
-- Verified directly against the installed Hyprland 0.56.0 binary
-- (/usr/bin/Hyprland, commit 36b2e0cfe0c6094dbc47bd42a437431315bb3087) via
-- `strings` — NOT copied from documentation. The binary embeds Hyprland's
-- own example config (its permission-grant Lua helper form) plus this
-- exact literal warning, quoted verbatim:
--
--   "Please note permission changes here require a Hyprland restart and
--    are not applied on-the-fly, for security reasons"
--
-- Confirmed facts (full verification transcript in
-- 11-QUICKSHELL-EVIDENCE.md, "Criterion 5 — screencopy feasibility"):
--   - The registered config-var is `ecosystem:enforce_permissions`,
--     default false (unrestricted) — this file is a no-op until flipped.
--   - The permission TYPE string for screen-capture is exactly
--     `screencopy` (lowercase); Hyprland's own shipped example also shows
--     a `plugin` type (unrelated to this file).
--   - The mode used here is `allow` only — never `ask` (D-12/T-11-20:
--     `ask` depends on an unresolved `hyprland-guiutils` popup-UI package
--     question, irrelevant to a feasibility probe; `deny` is never wanted
--     for a client this repo itself wants to work).
--   - Grants are read ONCE at compositor startup. `hyprctl reload` does
--     NOT apply a change here — a full Hyprland restart is required,
--     confirmed directly from the binary string above, not assumed.
--
-- This is NOT the standalone permissions config file the pre-11-05
-- ROADMAP wording named — that filename does not exist as a distinct
-- concept on 0.56.0 (see criterion 5's amendment in ROADMAP.md). The real
-- mechanism is this ordinary required Lua module: one permission-grant
-- call per client, plus the `ecosystem` option set via `hl.config`.
--
-- WHAT IS AND ISN'T VERIFIED (read before relying on this file):
--   - The MECHANISM (field names, type/mode strings, the
--     restart-not-reload requirement) is verified directly against the
--     installed binary, as above, and via the permission-grant calling-
--     convention spike in 13.1-LUA-FINDINGS.md.
--   - Every client identifier below is verified to be the CORRECT
--     binary for its consumer (`pacman -Ql`/`strings`/`pgrep` — see each
--     entry's own comment) — this is consumer *identification*, not a
--     live enforcement test.
--   - Live enforcement itself — that setting `enforce_permissions = true`
--     actually admits these exact clients and denies everyone else — was
--     DELIBERATELY NOT exercised in Phase 11 (2026-07-26, see git history
--     for that phase's own record). Phase 16 Plan 04 (D-16-09, OVER-04)
--     performed that proof: see 16-04-SUMMARY.md for the live restart,
--     the runtime `hyprctl getoption` readback, and the pass/fail result
--     for all five screencopy consumer paths.
--
-- ENFORCEMENT ENABLED: 2026-08-03, Phase 16 Plan 04 (D-16-09). The single
-- value below was flipped from `false` to `true` in this commit. Per the
-- restart-not-reload note above, a full Hyprland restart (log out, log
-- back in — never `hyprctl reload`) is required before this actually
-- takes functional effect; that restart and the resulting five-consumer
-- proof is this same plan's very next step (see 16-04-SUMMARY.md for the
-- live result). No other edit was required here — the four grants below
-- are unchanged from Phase 11's own consumer-identification work.
--
-- RECOVERY if the allow list turns out to be wrong (a legitimate
-- screencopy consumer breaks): open this file, restore the
-- `enforce_permissions` value below to its prior (unrestricted) setting,
-- log out and log back in (NOT `hyprctl reload` — see the
-- restart-not-reload note above; a reload does NOT apply a change here,
-- confirmed live by this same plan). Every consumer works again
-- immediately on the next session. Nothing is destroyed by getting the
-- allow list wrong — this is a one-value, fully-reversible toggle.
--
-- T-11-20 / T-13.1-02 (Elevation of Privilege): every client identifier
-- below is the EXACT absolute binary path, verified via
-- `pacman -Ql`/`strings`/`pgrep` — never a wildcard, `?`, `[`, `|` or
-- `.*` — even though Hyprland's own shipped Lua example
-- (/usr/share/hypr/hyprland.lua) uses a regular-expression alternation
-- for the same binaries (`/usr/(bin|local/bin)/grim`). A looser pattern
-- could let an unrelated binary in the same directory inherit a grant
-- meant for one specific tool. This port copies the vendor example's
-- CALL FORM only, never its path style — see 13.1-PERMISSION-REVIEW.md
-- for the recorded proof that no path here was broadened.

hl.config({ ecosystem = { enforce_permissions = true } })

-- Quickshell — this repo's own screencopy probe (criterion 5, D-12).
hl.permission({ binary = "/usr/bin/quickshell", type = "screencopy", mode = "allow" })

-- ── Pre-existing screencopy consumers on this machine (T-11-21) ──────
-- Enabling enforcement without these would break screenshots/screen-share
-- — a real regression against standing constraint 4's additive-only rule.
--
--   - grim: the actual capture binary invoked internally by hyprshot for
--     all four screenshot keybinds (capture-region.sh/-window.sh/-full.sh
--     all call `hyprshot`, which is a bash wrapper — verified via
--     `file`/`grep` on /usr/bin/hyprshot that it calls `grim -g ...`
--     itself; hyprshot issues no screencopy protocol calls of its own,
--     so hyprshot's own binary path would be the wrong client identifier).
hl.permission({ binary = "/usr/bin/grim", type = "screencopy", mode = "allow" })
--   - hyprpicker: confirmed via `strings /usr/bin/hyprpicker` to link
--     `zwlr_screencopy_manager_v1` directly (used for the Super+X color
--     picker and for record-toggle.sh's freeze-preview). Not named in
--     this plan's own text — found during this task's consumer
--     enumeration and added proactively (Rule 2: a real, disclosed
--     screencopy consumer this host already runs on a keybind).
hl.permission({ binary = "/usr/bin/hyprpicker", type = "screencopy", mode = "allow" })
--   - xdg-desktop-portal-hyprland: the actual running backend binary,
--     confirmed via `pgrep -af xdg-desktop-portal` against the live
--     process (`/usr/lib/xdg-desktop-portal-hyprland`) — NOT
--     `/usr/bin/hyprland-share-picker`, a separate picker-UI helper
--     shipped in the same package. This is the process that answers
--     `org.freedesktop.impl.portal.ScreenCast` for screen sharing
--     (confirmed: `hyprland.portal`'s `Interfaces=` line lists
--     `ScreenCast`, and `hyprland.portal`'s `DBusName=` matches the
--     running `/usr/lib/xdg-desktop-portal-hyprland` process, not
--     `xdg-desktop-portal-gtk`).
hl.permission({ binary = "/usr/lib/xdg-desktop-portal-hyprland", type = "screencopy", mode = "allow" })

-- ── Checked and deliberately excluded ────────────────────────────────
--   - slurp: confirmed via `strings /usr/bin/slurp` to carry NO
--     `screencopy` protocol references at all — it is a pure
--     region-selection overlay (outputs "X,Y WxH" text); the actual
--     freeze/capture in every script that uses it is done by a separate
--     tool (grim or hyprpicker, both already allowed above).
--   - gpu-screen-recorder (record-toggle.sh, SHOT-03, real binary path
--     /usr/bin/gpu-screen-recorder): `strings` on its binary shows no
--     direct `screencopy` protocol reference — it likely captures via
--     KMS/DRM (`gsr-kms-server`) or the portal's own ScreenCast path
--     (already covered by the portal entry above) rather than the
--     `wlr-screencopy` protocol directly. Phase 11 flagged this, not
--     guessed at it. Phase 16 Plan 04, Task 3 exercises it live under
--     this now-enabled enforcement (the fifth of the five screencopy
--     consumer paths that plan's human checkpoint proves) — see
--     16-04-SUMMARY.md for the recorded pass/fail result. If it failed,
--     a fifth grant for /usr/bin/gpu-screen-recorder was added below in
--     the same exact-absolute-path shape as the four above.
