-- hypr/.config/hypr/config/permissions.lua — Lua port of
-- config/permissions.conf (Phase 13.1, plan 13.1-07, D-12, 11-05).
-- Hyprland's dynamic-client permission manager.
--
-- Verified directly against the installed Hyprland 0.56.0 binary
-- (/usr/bin/Hyprland, commit 36b2e0cfe0c6094dbc47bd42a437431315bb3087) via
-- `strings` — NOT copied from documentation. The binary embeds Hyprland's
-- own example config (its permission-grant Lua helper form) plus this
-- exact literal warning, quoted verbatim:
--
--   "Please note permission changes here require a Hyprland restart and
--    are not applied on-the-fly, for security reasons"
--
-- Confirmed facts (full verification transcript in
-- 11-QUICKSHELL-EVIDENCE.md, "Criterion 5 — screencopy feasibility"):
--   - The registered config-var is `ecosystem:enforce_permissions`,
--     default false (unrestricted) — this file is a no-op until flipped.
--   - The permission TYPE string for screen-capture is exactly
--     `screencopy` (lowercase); Hyprland's own shipped example also shows
--     a `plugin` type (unrelated to this file).
--   - The mode used here is `allow` only — never `ask` (D-12/T-11-20:
--     `ask` depends on an unresolved `hyprland-guiutils` popup-UI package
--     question, irrelevant to a feasibility probe; `deny` is never wanted
--     for a client this repo itself wants to work).
--   - Grants are read ONCE at compositor startup. `hyprctl reload` does
--     NOT apply a change here — a full Hyprland restart is required,
--     confirmed directly from the binary string above, not assumed.
--
-- This is NOT the standalone permissions config file the pre-11-05
-- ROADMAP wording named — that filename does not exist as a distinct
-- concept on 0.56.0 (see criterion 5's amendment in ROADMAP.md). The real
-- mechanism is this ordinary required Lua module: one permission-grant
-- call per client, plus the `ecosystem` option set via `hl.config`.
--
-- WHAT IS AND ISN'T VERIFIED (read before relying on this file):
--   - The MECHANISM (field names, type/mode strings, the
--     restart-not-reload requirement) is verified directly against the
--     installed binary, as above, and via the permission-grant calling-
--     convention spike in 13.1-LUA-FINDINGS.md.
--   - Every client identifier below is verified to be the CORRECT
--     binary for its consumer (`pacman -Ql`/`strings`/`pgrep` — see each
--     entry's own comment) — this is consumer *identification*, not a
--     live enforcement test.
--   - Live enforcement itself — that setting `enforce_permissions = true`
--     actually admits these exact clients and denies everyone else — was
--     DELIBERATELY NOT exercised in Phase 11 (2026-07-26, see git history
--     for that phase's own record). Phase 16 Plan 04 (D-16-09, OVER-04)
--     performed that proof: see 16-04-SUMMARY.md for the live restart,
--     the runtime `hyprctl getoption` readback, and the pass/fail result
--     for all five screencopy consumer paths.
--
-- ENFORCEMENT ENABLED: 2026-08-03, Phase 16 Plan 04 (D-16-09). The single
-- value below was flipped from `false` to `true` in this commit. Per the
-- restart-not-reload note above, a full Hyprland restart (log out, log
-- back in — never `hyprctl reload`) is required before this actually
-- takes functional effect; that restart and the resulting five-consumer
-- proof is this same plan's very next step (see 16-04-SUMMARY.md for the
-- live result). No other edit was required here — the four grants below
-- are unchanged from Phase 11's own consumer-identification work.
--
-- RECOVERY if the allow list turns out to be wrong (a legitimate
-- screencopy consumer breaks): open this file, restore the
-- `enforce_permissions` value below to its prior (unrestricted) setting,
-- log out and log back in (NOT `hyprctl reload` — see the
-- restart-not-reload note above; a reload does NOT apply a change here,
-- confirmed live by this same plan). Every consumer works again
-- immediately on the next session. Nothing is destroyed by getting the
-- allow list wrong — this is a one-value, fully-reversible toggle.
--
-- T-11-20 / T-13.1-02 (Elevation of Privilege): every client identifier
-- below is the EXACT absolute binary path, verified via
-- `pacman -Ql`/`strings`/`pgrep` — never a wildcard, `?`, `[`, `|` or
-- `.*` — even though Hyprland's own shipped Lua example
-- (/usr/share/hypr/hyprland.lua) uses a regular-expression alternation
-- for the same binaries (`/usr/(bin|local/bin)/grim`). A looser pattern
-- could let an unrelated binary in the same directory inherit a grant
-- meant for one specific tool. This port copies the vendor example's
-- CALL FORM only, never its path style — see 13.1-PERMISSION-REVIEW.md
-- for the recorded proof that no path here was broadened.

hl.config({ ecosystem = { enforce_permissions = true } })

-- Quickshell — this repo's own screencopy probe (criterion 5, D-12).
hl.permission({ binary = "/usr/bin/quickshell", type = "screencopy", mode = "allow" })

-- ── Pre-existing screencopy consumers on this machine (T-11-21) ──────
-- Enabling enforcement without these would break screenshots/screen-share
-- — a real regression against standing constraint 4's additive-only rule.
--
--   - grim: the actual capture binary invoked internally by hyprshot for
--     all four screenshot keybinds (capture-region.sh/-window.sh/-full.sh
--     all call `hyprshot`, which is a bash wrapper — verified via
--     `file`/`grep` on /usr/bin/hyprshot that it calls `grim -g ...`
--     itself; hyprshot issues no screencopy protocol calls of its own,
--     so hyprshot's own binary path would be the wrong client identifier).
hl.permission({ binary = "/usr/bin/grim", type = "screencopy", mode = "allow" })
--   - hyprpicker: confirmed via `strings /usr/bin/hyprpicker` to link
--     `zwlr_screencopy_manager_v1` directly (used for the Super+X color
--     picker and for record-toggle.sh's freeze-preview). Not named in
--     this plan's own text — found during this task's consumer
--     enumeration and added proactively (Rule 2: a real, disclosed
--     screencopy consumer this host already runs on a keybind).
hl.permission({ binary = "/usr/bin/hyprpicker", type = "screencopy", mode = "allow" })
--   - xdg-desktop-portal-hyprland: the actual running backend binary,
--     confirmed via `pgrep -af xdg-desktop-portal` against the live
--     process (`/usr/lib/xdg-desktop-portal-hyprland`) — NOT
--     `/usr/bin/hyprland-share-picker`, a separate picker-UI helper
--     shipped in the same package. This is the process that answers
--     `org.freedesktop.impl.portal.ScreenCast` for screen sharing
--     (confirmed: `hyprland.portal`'s `Interfaces=` line lists
--     `ScreenCast`, and `hyprland.portal`'s `DBusName=` matches the
--     running `/usr/lib/xdg-desktop-portal-hyprland` process, not
--     `xdg-desktop-portal-gtk`).
hl.permission({ binary = "/usr/lib/xdg-desktop-portal-hyprland", type = "screencopy", mode = "allow" })

-- ── Checked and deliberately excluded ────────────────────────────────
--   - slurp: confirmed via `strings /usr/bin/slurp` to carry NO
--     `screencopy` protocol references at all — it is a pure
--     region-selection overlay (outputs "X,Y WxH" text); the actual
--     freeze/capture in every script that uses it is done by a separate
--     tool (grim or hyprpicker, both already allowed above).
--   - gpu-screen-recorder (record-toggle.sh, SHOT-03, real binary path
--     /usr/bin/gpu-screen-recorder): `strings` on its binary shows no
--     direct `screencopy` protocol reference — it likely captures via
--     KMS/DRM (`gsr-kms-server`) or the portal's own ScreenCast path
--     (already covered by the portal entry above) rather than the
--     `wlr-screencopy` protocol directly. Phase 11 flagged this, not
--     guessed at it. Phase 16 Plan 04, Task 3 exercises it live under
--     this now-enabled enforcement (the fifth of the five screencopy
--     consumer paths that plan's human checkpoint proves) — see
--     16-04-SUMMARY.md for the recorded pass/fail result. If it failed,
--     a fifth grant for /usr/bin/gpu-screen-recorder was added below in
--     the same exact-absolute-path shape as the four above.

-- ── hyprpm plugin-load grant (Phase 17 plan 04, D-33/AMB-02) ──────────
-- [Rule 1 fix, found live during this plan's Task 3 fault injection, NOT
-- anticipated by 17-RESEARCH.md or 17-CONTEXT.md]: with
-- ecosystem.enforce_permissions on and no `plugin`-type grant, hyprpm
-- signalling the live compositor to load a plugin (via `hyprpm reload`,
-- and via `hyprpm update`'s own implicit load step once it succeeds)
-- pops a real GUI `hyprland-dialog` ("An application /usr/bin/hyprpm is
-- trying to load a plugin... Allow/Deny") and BLOCKS the hyprpm process
-- until a human clicks it — live-reproduced this session: a bare
-- `hyprpm reload` hung past a 120s bound with no default action. This
-- directly threatens AMB-02 criterion 2's "never blocks waiting for a
-- confirmation" guarantee for both install.sh's guarded block (on a
-- re-run against an already-live session) and hyprpm-complete.sh (every
-- normal login once the plugin needs a (re)load).
--
-- This is the EXACT grant Hyprland's own shipped example names for this
-- exact tool — /usr/share/hypr/hyprland.lua line 78 carries, commented
-- out: `hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")`.
-- This port keeps that example's CALL FORM only, not its regex path
-- style, per this file's own established convention above (T-11-20).
--
-- Per this file's own documented rule, this grant is read once at
-- compositor startup and needs a Hyprland restart (not `hyprctl reload`)
-- to take effect — hyprpm-complete.sh and install.sh's guarded block
-- both additionally bound every hyprpm invocation with `timeout` as
-- defense in depth for the window before that restart, and permanently
-- afterward, so this optional/best-effort dependency can never hang a
-- login or an install re-run even if a grant is ever missing.
hl.permission({ binary = "/usr/bin/hyprpm", type = "plugin", mode = "allow" })

-- ── Hyprland self-load grant — TESTED AND REVERTED (Phase 17 plan 05,
-- D-35) ──────────────────────────────────────────────────────────────
-- Was briefly added to test whether a Lua-config-issued
-- `hl.plugin.load()` (hypr/.config/hypr/config/dynamic-cursors.lua) is
-- routed through the same DynamicPermissionManager confirm-dialog flow
-- as an external IPC request, keyed to /usr/bin/Hyprland as the
-- "requesting binary". CONFIRMED, live, after a real restart: with this
-- grant present, the user was prompted with a real Allow/Deny dialog for
-- the dynamic-cursors plugin at login, and again when hypridle's
-- `loginctl lock-session` triggered hyprlock (600s idle) — a genuine
-- steady-state regression, a human clicking a permission dialog on every
-- login and every idle-lock. Removed. The grant provided no offsetting
-- benefit: `hl.plugin.load()` still does not actually load the plugin on
-- this Hyprland build regardless of the grant (17-05-SUMMARY.md's A2
-- finding — every tested call shape returns without error but never
-- reaches dlopen-level validation; a nonexistent path behaves
-- byte-identically to the real one). Root cause, reasoned from this
-- evidence (not independently confirmed against the dialog's own literal
-- text, which no log or journal entry captured on this build): on a real
-- cold boot, dynamic-cursors.lua's own guard finds the plugin NOT yet
-- loaded on the very first config pass (hyprpm-complete.sh's real load
-- is async, from autostart, and hasn't run yet) and calls
-- `hl.plugin.load()` for real — with this grant, that call could
-- actually render a confirm dialog (it silently failed to render at all
-- in every nested-harness test run without this grant); without a
-- response, the request stays pending, and hyprlock's own session-lock
-- surface appears to be the next point Hyprland has an opportunity to
-- show it — the same single pending request, not a second one. The
-- module's `pcall`-wrapped self-load attempt remains in place (harmless,
-- silently inert without this grant, matching Task 1's own nested
-- testing throughout); the real, working load path continues to be
-- hyprpm via hyprpm-complete.sh, which already holds its own,
-- unaffected /usr/bin/hyprpm grant above.
-- hl.permission({ binary = "/usr/bin/Hyprland", type = "plugin", mode = "allow" })
--
-- CORRECTED DIAGNOSIS, same session: the grant above targeted the wrong
-- caller identity. The dialog's own verbatim text, obtained directly
-- from the user (never captured by any log or journal entry on this
-- build): "An application config is trying to load a plugin
-- /var/cache/hyprpm/aorus/dynamic-cursors/dynamic-cursors.so" — the
-- caller identity is the literal string `config`, not a binary path at
-- all. Confirmed against this machine's installed Hyprland dev headers
-- (`/usr/include/hyprland/src/managers/permissions/
-- DynamicPermissionManager.hpp`): `eSpecialPidTypes` defines
-- `SPECIAL_PID_TYPE_CONFIG = -3` as a distinct caller class from a real
-- process PID/binary path, `clientPermissionModeWithString(pid_t pid,
-- const std::string& str, eDynamicPermissionType permission)` is
-- documented "for plugins for now" (i.e. Lua-config-issued
-- `hl.plugin.load()` calls are matched by STRING key, not by resolving a
-- caller binary path at all), and `eDynamicPermissionAllowMode` includes
-- `PERMISSION_RULE_ALLOW_MODE_PENDING, // popup is open` — the call
-- doesn't fail or no-op, it PARKS awaiting an answer. This fully explains
-- every symptom the earlier (wrong) `/usr/bin/Hyprland` grant attempt
-- observed: `pcall` sees a normal return because C++ never raises past
-- the pending promise, zero log output because nothing failed, and a
-- nonexistent path behaves identically to a real one because the call
-- never reaches path/dlopen validation — it's stopped at the permission
-- gate before that. See 17-05-SUMMARY.md's corrected A2 finding.
--
-- `binaryPathRegex` is a real RE2 regex (re2::RE2 `m_binaryRegex`), so
-- `config` un-anchored could incidentally match a hypothetical future
-- binary path merely containing that substring (e.g. some
-- "*-config-tool" grant added later) — anchored to `^config$` so it can
-- only ever match the exact literal identity Hyprland uses for its own
-- config-issued calls, nothing else.
hl.permission({ binary = "^config$", type = "plugin", mode = "allow" })
