# ~/.dotfiles/matugen/.config/matugen/templates/fuzzel-colors.ini

[colors]
background=141218e6
text=e7e0e8ff
match=d2bcfdff
selection=2b292fff
selection-text=e7e0e8ff
selection-match=d2bcfdff
border=d2bcfdff