# See https://wiki.hypr.land/Configuring/Monitors/
monitor=DP-1, 2560x1440@165, 0x0, 1

# See https://wiki.hypr.land/Configuring/XWayland/#hidpi-xwayland
# for fixing scaling

xwayland {
    # unscale XWayland
    force_zero_scaling = true
}

# toolkit-specific scale
# env = GDK_SCALE,2
