# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

# exec-once = $terminal
# exec-once = uwsm-app -- swww-daemon --format=xrgb
exec-once = uwsm-app -- swaybg -m fill -i $HOME/Pictures/wallpapers/982990.jpg
exec-once = uwsm-app -- waybar