# Gruvbox Dark — Yazi theme
"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

[mgr]
cwd = { fg = "#d79921" }
tab_active = { fg = "#282828", bg = "#d79921", bold = true }
tab_inactive = { fg = "#504945", bg = "#3c3836" }
border = { fg = "#504945" }
find_keyword = { fg = "#fe8019", bold = true, underline = true }
find_position = { fg = "#d79921", italic = true }
marker_selected = { fg = "#fe8019", bg = "#fe8019" }
marker_copied = { fg = "#d79921", bg = "#d79921" }
marker_cut = { fg = "#fb4934", bg = "#fb4934" }
count_selected = { fg = "#282828", bg = "#fe8019", bold = true }
count_copied = { fg = "#282828", bg = "#d79921", bold = true }
count_cut = { fg = "#282828", bg = "#fb4934", bold = true }

[mode]
normal = { fg = "#282828", bg = "#d79921", bold = true }
select = { fg = "#282828", bg = "#fe8019", bold = true }
unset = { fg = "#282828", bg = "#fb4934", bold = true }

[status]
separator_open = { fg = "#3c3836" }
separator_close = { fg = "#3c3836" }
progress_label = { fg = "#ebdbb2", bold = true }
progress_normal = { fg = "#d79921" }
progress_error = { fg = "#fb4934" }
perm_read = { fg = "#d79921" }
perm_write = { fg = "#fe8019" }
perm_exec = { fg = "#fb4934" }
perm_sep = { fg = "#504945" }

[input]
border = { fg = "#d79921" }
title = { fg = "#d79921" }
value = { fg = "#ebdbb2" }
selected = { reversed = true }

[pick]
border = { fg = "#d79921" }
active = { fg = "#d79921", bold = true }
inactive = { fg = "#ebdbb2" }

[confirm]
border = { fg = "#d79921" }
title = { fg = "#d79921" }
content = { fg = "#ebdbb2" }
list = { fg = "#ebdbb2" }
btn_yes = { fg = "#282828", bg = "#d79921", bold = true }
btn_no = { fg = "#282828", bg = "#504945", bold = true }

[completion]
border = { fg = "#d79921" }
active = { fg = "#d79921", bold = true }
inactive = { fg = "#504945" }

[help]
on = { fg = "#d79921" }
run = { fg = "#fe8019" }
desc = { fg = "#ebdbb2" }
hovered = { reversed = true, bold = true }
footer = { fg = "#504945", italic = true }

[notify]
title_info = { fg = "#d79921" }
title_warn = { fg = "#fe8019" }
title_error = { fg = "#fb4934" }
