# ~/.dotfiles/hyprland/.config/hypr/hypridle.conf

general {
    # Command to run when locking
    lock_cmd = pidof hyprlock || hyprlock
    # Lock the screen before the system goes to sleep
    before_sleep_cmd = loginctl lock-session
    # Wake up the display when waking up from sleep
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Lock screen after 5 minutes
listener {
    timeout = 300 
    on-timeout = loginctl lock-session
}

# Turn off the display after 5.5 minutes
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}