# ~/.dotfiles/hyprland/.config/hypr/monitors.conf
# Syntax: monitor=name,resolution,position,scale
# Leaving the name empty applies this to the first detected monitor
monitor=DP-1,2160x1440@165,auto,1

# See https://wiki.hypr.land/Configuring/XWayland/#hidpi-xwayland
# for fixing scaling
xwayland {
    # unscale XWayland
    force_zero_scaling = true
}